### ISSUE TITLE
Wallet password creation field should have no validation except for repetition

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/ziggurat-ui#106]
It should be possible to use any string as a password for a wallet (including `""`). Also, there should be two fields, such that the user has to correctly enter the new password twice to confirm it.

Reasoning: using a password to secure a seed phrase is technically optional and only provides security enhancement in certain scenarios, so it's not something that should be enforced. However, losing the optional password is still catastrophic if seed phrase is not backed up, so making 100% sure the original password was not created with an error is still very important.

**Comment by 0x70b1a5** [comment]
#111
