### ISSUE TITLE
Wallet: token sends are not clear about decimal points

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/ziggurat-ui#139]
This is not a bug, just a design choice. Right now, the wallet token send modal automatically adds 18 decimal points to the entered value. I find this a bit unclear and think we need to more clearly surface the exact amount of tokens being sent. For example, I've seen other wallets put the exact number (with full accuracy/decimals&commas) in gray above the input box. 

It'd also be good if the frontend performed some basic validation of the input and didn't allow you to generate the transaction if you enter a value for your send that's higher than the amount of tokens you own. I'd even want to add some kind of allowance for gas here, only for ZIGs -- for example, if you have exactly 1 ZIG in your wallet, and you try to send exactly 1 ZIG, you won't be able to pay for gas. Just padding out the default gas allowance we use now (0.000000000001000000 ZIG) (which will change in the future) in the frontend validation would resolve this.

**Comment by hosted-fornet** [comment]
Metamask solves this by having different units for ETH and gas fees -- gwei iirc? It is bad to make users read/write a number with 18 zeroes in it -- v easy to mess up --, so it probably makes sense to do something like this as well.

**Comment by 0x70b1a5** [comment]
I recall some talk about this in the group chat but I can't find it. What was decided for the name?

**Comment by hosted-fornet** [comment]
I believe it was Bar.

**Comment by dr-frmr** [comment]
Can always change later, that's a good placeholder I think

**Comment by willbach** [comment]
<img width="274" alt="Screen Shot 2023-01-13 at 12 14 46 PM" src="https://user-images.githubusercontent.com/7759384/212318091-44e0d5b7-2140-4b5e-be1a-d0149b76b9b7.png">
how's this?

**Comment by willbach** [comment]
<img width="278" alt="Screen Shot 2023-01-13 at 12 15 10 PM" src="https://user-images.githubusercontent.com/7759384/212318204-10e4331b-d3d4-42ca-86ac-f1256d46622d.png">
and the error
