### ISSUE TITLE
compiler errors (for contracts or test-steps/configs/...) need more room to be displayed

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/ziggurat-ui#159]
The toast-replacements in the lower left don't cut it for compiler errors. Since we expect to have users compiling contracts, etc in the IDE, we need some fairly front-and-center way to display compiler errors, preferably in a way where the user can also view the code that led to the error for side-by-side or overlaid or whatever editing.

If it is hard to distinguish what updates are compiler errors, the backend can be changed to give updates that are more clearly marked as this type of error -- just let me know what would make your life easy.

**Comment by 0x70b1a5** [comment]
Been thinking about how to do this. Obviously if we want to replace terminal windows, we need a display that sits next to the rest of the data on screen. But it seems like it should not be restricted to a single tab. That means it's going to be top-level like the sidebar or the tab menu. 

Text data is also very space hungry. But errors are not always present. So the space allocated to errors should be something that can be expand/collapsed. 

What if there was a secondary sidebar that held a list of recent errors? It could be about the same width as the existing sidebar, and it would only contain a list of error messages.

**Comment by hosted-fornet** [comment]
I don't have much of an aesthetic sensibility for these things until I can see it. I think a sidebar sounds reasonable. Is there a reason it can't be combined with the existing sidebar?

Paging @timlucmiptev for opinions.

**Comment by 0x70b1a5** [comment]
It depends on what you mean by "they don't cut it". Is there not enough info in the toast? Is the info squeezed into too small of a space? etc.

**Comment by hosted-fornet** [comment]
Too much info in too small a space -- sorry for imprecise language. The compiler errors might have ~10 lines of code, which are each fairly long (file paths, or 10s of words).

**Comment by 0x70b1a5** [comment]
#178
