### ISSUE TITLE
some default state views should ship with all projects

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/ziggurat-ui#175]
Let's brainstorm some common use-cases over next couple days.

Here are some to start with:

## Chain

* `transactions:(~(got by -) 0x0)`
* `chain:(~(got by -) 0x0)`
* ```hoon
   ::  get all items with contract source=zigs
   ^-  (map @ux item:smart)
   =/  source=@ux  0x74.6361.7274.6e6f.632d.7367.697a
   %-  ~(gas by *(map @ux item:smart))
   %+  murn  ~(tap by chain:(~(got by -) 0x0))
   |=  [id=@ux @ =item:smart]
   ?-    -.item  ::  dumb pattern to satisfy compiler
       %&
      ?.  =(source source.p.item)  ~
     `[id item]
       %|
      ?.  =(source source.p.item)  ~
     `[id item]
   ==
   ```
   with imports
   ```
   smart  /lib/zig/sys/smart
   ```
   (untested)
* ```hoon
   ::  get all items held by who=~nec
   ^-  (map @ux item:smart)
   =/  who=@p  ~nec
   =/  who-address=@ux
     %.  [%global [who %address]
     ~(got bi:mip configs:test-globals)
   %-  ~(gas by *(map @ux item:smart))
   %+  murn  ~(tap by chain:(~(got by -) 0x0))
   |=  [id=@ux @ =item:smart]
   ?-    -.item  ::  dumb pattern to satisfy compiler
       %&
      ?.  =(who-address holder.p.item)  ~
     `[id item]
       %|
      ?.  =(who-address holder.p.item)  ~
     `[id item]
   ==
   ```
   with imports
   ```
   mip  /lib/mip
   smart  /lib/zig/sys/smart
   ```
   (untested)

## Agent

* %wallet
   `metadata-store`
* %wallet
   ```hoon
   ::  get items held by who=~nec
   ^-  (map @ux book:wal)
   =/  who=@p  ~nec
   =/  who-address=@ux
     %.  [%global [who %address]
     ~(got bi:mip configs:test-globals)
   (~(got by tokens) who-address)
   ```
   with imports
   ```
   wal  /sur/zig/wallet
   ```

**Comment by hosted-fornet** [comment]
I am thinking it may make sense to have these live in the backend and expose an endpoint for FE to scry them out. That way if something needs to get updated or added, a hooner can do it. Really, these should probably exist as part of the configuration files that get loaded in when a project is added; that way %pokur can have some as well.

**Comment by hosted-fornet** [comment]
https://github.com/uqbar-dao/dev-suite/pull/38 implements the backend

Went with /zig/state-views rather than /zig/vue because the other dirs in /zig are named in non-three-char-ways -- otherwise would've done /zig/vue

**Comment by 0x70b1a5** [comment]
Right - 3char is for top level ...
