### ISSUE TITLE
errors pane (and related) issues

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/ziggurat-ui#178]
1. error pane is not populated with error at first -- user must change the dimension of the pane to see the error
2. error pane can be dragged up past top of screen: the user can then not change the size of the error pane any more
3. errors do not scroll up once the pane is filled
4. it may be more useful to users to have most recent error at the top, rather than the bottom

**Comment by hosted-fornet** [comment]
re to 1:

![230227-contract-error-in-toast](https://user-images.githubusercontent.com/79381743/221767599-a40d7185-8fcc-4a2d-959a-3049a9fd8862.png)

**Comment by 0x70b1a5** [comment]
- should be dojo view by default
- most recent err now at top
- scrolling possible
