### ISSUE TITLE
Should remove `supply` and `cap` fields from metadata forms

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/ziggurat-ui#25]
However, the %populate poke to backend must still have these values. We have hardcoded values for our "fake data" that allows us to pre-populate these projects. The default address (which should be settable by wallet?) should be the one minter, and the project should be mintable. For fungible, let's remove the decimals field too and just put `1` there. They can edit in their metadata grain. I like the idea of making the starting form way simpler.

Fungible:
Supply is `400`
Cap is `~`
Mintable is `&`
Minters is the set of just their address

NFT:
Supply is `2`
Cap is `~`
Mintable is `&`
Minters is the set of just their address

**Comment by dr-frmr** [comment]
Oh, deployer should just be our set address as well

**Comment by willbach** [comment]
https://github.com/uqbar-dao/ziggurat-ui/pull/27
