### ISSUE TITLE
Full Hoon syntax highlighting

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/ziggurat-ui#26]
Github appears to use this repo to generate their hoon syntax highlighting, which I find very good: https://github.com/pkova/hoon-grammar/tree/262617397fd058a8cc294ac7ece0b55e76638e12

This goes through Linguist, which I assume has an analogue in JS: https://github.com/github/linguist/

We should try to use this or a very similar ruleset

**Comment by willbach** [comment]
https://github.com/uqbar-dao/ziggurat-ui/pull/27
