### ISSUE TITLE
Two unpleasant bugs that could really use fixing before Sunday

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/ziggurat-ui#35]
First one is new with most recent update:

Dots are added to grain labels improperly:
<img width="477" alt="Screen Shot 2022-09-24 at 12 53 59 AM" src="https://user-images.githubusercontent.com/93405247/192080614-029700f2-bbf1-4565-9161-20b5823cf0a4.png">

Should not have dots in the text labels

Second one is a long-standing bug. If you tab to a non-code tab, i.e. the tests tab, and then click over to a code tab, there is no syntax highlighting. It seems that the code highlighting only takes effect if the tab before the current one was also a code tab. The syntax highlighting when active looks good now, though!

**Comment by willbach** [comment]
#36
