### ISSUE TITLE
Unsaved files do not communicate unsaved status

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/ziggurat-ui#47]
I am thinking of at least 4 things:
Unsaved files
- should display (*) in the tab name 
- be a different color or something on the sidebar file list
- display a "Save" button in bottom right of screen
- prompt user to confirm tab close with the standard "Changes may not be saved" dialog

**Comment by willbach** [comment]
all good, I think (2) could just be the same as (1). Put an asterisk after the file name in both top tab and sidebar
